### ISSUE TITLE
lambdaにどうやってファイルを渡すべきか - API経由の場合

### ISSUE THREAD

**Issue by Imfloppy** [s2m2/serverless-workshop#1]
簡単に思いつく方法としては
- S3
- Amazon API Gateway を使い、dataとしてPOSTする

かと思います。

ファイル圧縮を考えた場合、何度もS3を経由するのも不自然な気がして
できればAPIを使ったやり方にしたいと考えていますが、POSTしたデータを拾ってくる方法がわかりません。

例えば、pythonだと

```
def lambda_hander(event, context):
   ...
```

のeventあたりから取ってこれそうだと思うのですが、もし何か心当たりがあったら教えてもらえると助かります:pray:

---

いちおうドキュメントはあさってみたのですがいまいちつかめません:pensive:

**Comment by hiroki8080** [comment]
一つのファイルを複数のLambdaAPIで読み込むのでS3が良いかなと思います。
ひとまず各担当部分はS3経由というルールにした方がわかりやすいかもですね。

すみません、まだeventの辺りはこれから調べてみます。

**Comment by hiroki8080** [comment]
まだよくわかっていないですが、S3からLambdaを呼び出すような流れになりそうですね。
この辺りが参考になるかも。
http://docs.aws.amazon.com/ja_jp/lambda/latest/dg/intro-core-components.html

**Comment by hiroki8080** [comment]
eventはjson形式の値になるみたいです。
`{
    "hoge": "fuga"
}`
とAPIに送った場合には、
`event['hoge']`
で値が取れるようです。

**Comment by Imfloppy** [comment]
ありがとうございます！
私も情報をjson形式でとってくるところまではわかったのですが
postしたデータ部分をとってくる点が疑問でした。

本番環境でもう少しトライしてみます。
